cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
    credentials:
      access-key: AKIAYOAGHPLJTWZLYTQJ
      secret-key: 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

application:
  bucket:
    name: testbucket1231312