server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:/db/migration/schema, classpath:/db/migration/data
  h2:
    console:
      enabled: true
      path: /h2

