server:
  port: 8080

---

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/school?serverTimezone=UTC&useSSL=false&autoReconnect=true
    username: admin
    password: admin
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect