#!/usr/bin/env bash

declare  PUBLICATION_YEAR_INTERVAL="1970-2018"
declare  PRODUCT_TYPE="books"       #could be journals

declare  MANAGEMENT_CATALOG_NO="MANAGEMENT-27382"
declare  COMPUTER_SCIENCE_CATALOG_NO="COMPUTER_SCIENCE-27364"
declare  PSYCHOLOGY_CATALOG_NO="PSYCHOLOGY-27388"
declare  ECONOMICS_CATALOG_NO="ECONOMICS-27386"
declare  MEDICINE_CATALOG_NO="MEDICINE-27336"

declare  ENGINEERING_CATALOG_NO="ENGINEERING-27370"
declare  BIOLOGY_CATALOG_NO="BIOLOGY-27346"
declare  PHYSICS_CATALOG_NO="PHYSICS-27378"
declare  TOXICOLOGY_CATALOG_NO="TOXICOLOGY-27358"
declare  VETERINARY_CATALOG_NO="VETERINARY-27344"

declare  MATHEMATICS_CATALOG_NO="MATHEMATICS-27376"
declare  PHARMACOLOGY_CATALOG_NO="PHARMACOLOGY-27356"
declare  CHEMISTRY_CATALOG_NO="CHEMISTRY-27362"
declare  MICROBIOLOGY_CATALOG_NO="MICROBIOLOGY-27352"
declare  SOCIAL_SCIENCE_CATALOG_NO="SOCIAL_SCIENCE-27390"

declare  MATERIAL_SCIENCE_CATALOG_NO="MATERIAL_SCIENCE-27374"

declare -a CATALOGS_IDS=($MANAGEMENT_CATALOG_NO
                         $COMPUTER_SCIENCE_CATALOG_NO
                         $PSYCHOLOGY_CATALOG_NO
                         $ECONOMICS_CATALOG_NO
                         $MEDICINE_CATALOG_NO
                         $ENGINEERING_CATALOG_NO
                         $BIOLOGY_CATALOG_NO
                         $PHYSICS_CATALOG_NO
                         $TOXICOLOGY_CATALOG_NO
                         $VETERINARY_CATALOG_NO
                         $MATHEMATICS_CATALOG_NO
                         $PHARMACOLOGY_CATALOG_NO
                         $CHEMISTRY_CATALOG_NO
                         $MICROBIOLOGY_CATALOG_NO
                         $SOCIAL_SCIENCE_CATALOG_NO
                         $MATERIAL_SCIENCE_CATALOG_NO
                         )

declare -a INTERESTS=("BIOLOGY" "CHEMISTRY" "COMPUTER_SCIENCE" "ECONOMICS"
        "ENGINEERING" "MANAGEMENT" "MATERIAL_SCIENCE" "MATHEMATICS" "MEDICINE" "MICROBIOLOGY"
        "PHARMACOLOGY" "SOCIAL_SCIENCE" "TOXICOLOGY" "VETERINARY")

declare -a PAYMENT_LATE_REASONS=("I was sick, sorry." "Forgot about the book I took." "Lost the book and tried to find it all this time long." "I don't want to have debts in this library :)"
        "I'm so stupid - just paid this invoice" "" "" "" "" "Donations")

declare -a VISITOR_CATERORIES=("STUDENT" "ENGINEER" "RETIRED" "WANTED" "UNEMPLOYED" "OTHER")

declare PAYMENT_COUNT=1500
declare DEBT_COUNT=PAYMENT_COUNT

declare BOOK_ID=0
declare BOOKNUMBER=0

declare PENALTY_ID=0
declare VISITOR_ID=0
declare PAYMENT_ID=0

declare BOOK_DATA_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/BOOK_DATA/"
declare BOOK_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/BOOK/"
declare BOOK_IMAGE_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/BOOK_IMAGES/"

declare DEBTS_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/DEBTS/"
declare HISTORY_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/HISTORY/"
declare PAYMENT_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/PAYMENTS/"

declare PENALTY_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/PENALTY_PLANS/"
declare VISITOR_OUTPUT_FILENAME_PREFIX="./FINAL_RESULT/VISITORS/"

declare OUTPUT_FILENAME_POSTFIX=".yml"
