spring:
  profiles:
    active: dev
  http:
    log-request-details: true

management:
  endpoints:
    web:
      cors:
        allowed-methods: GET, POST, PUT, DELETE, OPTIONS
        max-age: 3600s
        allowed-origins: '*'
        allow-credentials: true

server:
  port: 8080
  tomcat:
    max-threads: 30

---
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: SA
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /dbconsole
  data:
    mongodb:
      host: localhost
      port: 27017
      database: booklib
    mongock:
      changelog-path: "com.booklibrary.app.configuration.changelogs"

---