version: '3'

services:
  mysql:
    container_name: "mysql"
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=30M
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=school
    volumes:
      - "/etc/timezone:/etc/timezone:ro"                    # fix docker container date/time
      - "/etc/localtime:/etc/localtime:ro"
      - "./volumes/mysql_plugins:/usr/lib/mysql/plugin:rw"
      - "./volumes/mysql_files:/var/lib/mysql-files:rw"
      - "./volumes/mysql-dump:/docker-entrypoint-initdb.d:rw"
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"

  app:
    container_name: "storedprocexample"
    hostname: localhost
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - "8081:8080"