CREATE TABLE IF NOT EXISTS teachers (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(50),
	lastname VARCHAR(50),
	email VARCHAR(50) UNIQUE,
	birthdate DATE

) ENGINE = InnoDB DEFAULT CHARSET = UTF8;